on:
  push:
  pull_request:
name: "testing"
jobs:
  debug:
    name: debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: hmarr/debug-action@v2
      - run: ls -la .
